/* Draft A Lore — explainable POV and pacing analytics */
DAL = DAL || {};

DAL.PACING_TARGETS={
  'Fantasy':[38,62],'Science Fiction':[42,64],'Romance':[42,62],'Mystery':[52,72],'Thriller':[62,82],'Horror':[50,74],'Historical':[36,58],'Adventure':[58,78],'Literary Fiction':[30,55],'Young Adult':[52,74],'Children’s':[56,80],'Dungeons & Dragons':[58,80],'Tabletop RPG':[58,80],'Interactive Fiction':[56,80],default:[42,68]
};
DAL.projectPacingTarget=function(proj){var ranges=(proj.genres||[]).map(function(genre){return DAL.PACING_TARGETS[genre];}).filter(Boolean);if(!ranges.length)return DAL.PACING_TARGETS.default.slice();return [Math.round(ranges.reduce(function(sum,range){return sum+range[0];},0)/ranges.length),Math.round(ranges.reduce(function(sum,range){return sum+range[1];},0)/ranges.length)];};
DAL.analyzePacing=function(html){
  var text=DAL.continuityText(html),words=text.match(/[A-Za-z0-9’'-]+/g)||[],sentences=text.split(/[.!?]+(?:[”"']|\s|$)/).map(function(value){return value.trim();}).filter(Boolean),paragraphs=String(html||'').split(/<\/(?:p|div|blockquote|li)>|\n\s*\n/ig).map(DAL.continuityText).filter(Boolean);
  var quoted=0,match,re=/[“"]([^”"]+)[”"]/g;while((match=re.exec(text)))quoted+=match[1].length;
  var actionWords={ran:1,run:1,sprinted:1,jumped:1,struck:1,fought:1,hit:1,slashed:1,fired:1,shot:1,grabbed:1,threw:1,crashed:1,burst:1,fled:1,chased:1,attacked:1,dodged:1,shouted:1,screamed:1};
  var action=words.reduce(function(count,word){return count+(actionWords[DAL.continuityKey(word)]?1:0);},0),wordCount=words.length,avgSentence=sentences.length?wordCount/sentences.length:0,avgParagraph=paragraphs.length?wordCount/paragraphs.length:0,dialogue=text.length?quoted/text.length:0,actionDensity=wordCount?action*100/wordCount:0;
  var score=wordCount?Math.round(Math.max(0,Math.min(100,50+(18-avgSentence)*2+(dialogue-.22)*38+actionDensity*3+(65-avgParagraph)*.12))):0;
  return {words:wordCount,sentences:sentences.length,paragraphs:paragraphs.length,avgSentence:Number(avgSentence.toFixed(1)),avgParagraph:Number(avgParagraph.toFixed(1)),dialogueRatio:Number(dialogue.toFixed(3)),actionDensity:Number(actionDensity.toFixed(1)),sceneBreaks:(String(html||'').match(/(?:<hr\b|(?:^|\n)\s*(?:\*\s*\*\s*\*|---+)\s*(?:\n|$))/gim)||[]).length,score:score};
};
DAL.povRecords=function(proj){return (DAL.continuityRecords?DAL.continuityRecords(proj):[]).filter(function(record){return record.kind==='Character'||record.kind==='Shared character';});};
DAL.povMentions=function(text,record){var total=DAL.continuityMentions(text,record.name).length;(record.aliases||[]).forEach(function(alias){total+=DAL.continuityMentions(text,alias).length;});return total;};
DAL.suggestPOV=function(proj,ch){var text=DAL.continuityText(ch.contentHTML),first=(text.match(/\b(I|me|my|mine|myself)\b/gi)||[]).length,records=DAL.povRecords(proj),ranked=records.map(function(record){return{record:record,count:DAL.povMentions(text,record)};}).sort(function(a,b){return b.count-a.count;});if(first>=5&&(!ranked[0]||first>ranked[0].count*2))return{id:'first-person',name:'First-person narrator',count:first};return ranked[0]&&ranked[0].count?{id:ranked[0].record.id,name:ranked[0].record.name,count:ranked[0].count}:null;};
DAL.storyAnalytics=function(proj){var target=DAL.projectPacingTarget(proj),chapters=(proj.chapters||[]).slice().sort(function(a,b){return Number(a.order||0)-Number(b.order||0);}),rows=chapters.map(function(chapter){var pacing=DAL.analyzePacing(chapter.contentHTML);return{chapter:chapter,pacing:pacing,suggestion:DAL.suggestPOV(proj,chapter)};});var weighted=rows.reduce(function(sum,row){return sum+row.pacing.score*row.pacing.words;},0),words=rows.reduce(function(sum,row){return sum+row.pacing.words;},0);return{target:target,rows:rows,overall:words?Math.round(weighted/words):0,words:words};};

DAL.renderStoryAnalytics=function(proj){
  var report=DAL.storyAnalytics(proj),povs=DAL.povRecords(proj),maxMention=1;
  report.rows.forEach(function(row){povs.forEach(function(record){maxMention=Math.max(maxMention,DAL.povMentions(DAL.continuityText(row.chapter.contentHTML),record));});});
  var genre=(proj.genres||[]).join(', ')||'general fiction',html='<div class="story-analytics"><div class="section-header"><div><div class="section-title">POV & Pacing</div><p class="writer-muted">Explainable signals from your manuscript—not an AI verdict. Genre guidance uses broad commercial-fiction ranges and should support, not overrule, your style.</p></div></div>';
  html+='<div class="analytics-hero"><div class="card"><span>Project pace</span><strong>'+report.overall+'</strong><small>target '+report.target[0]+'–'+report.target[1]+' · '+DAL.escapeHtml(genre)+'</small></div><div class="card"><span>Manuscript</span><strong>'+report.words.toLocaleString()+'</strong><small>words across '+report.rows.length+' chapter'+(report.rows.length===1?'':'s')+'</small></div><div class="card"><span>Reading rhythm</span><strong>'+(report.overall>report.target[1]?'Fast':report.overall<report.target[0]?'Measured':'Balanced')+'</strong><small>relative to selected genres</small></div></div>';
  if(!report.rows.length)return html+'<div class="empty-state"><h3>No chapters to analyze</h3><p>Add manuscript chapters first.</p></div></div>';
  html+='<h3>POV heatmap</h3><p class="writer-muted">Brighter cells mean the character is named more often. Set the intended POV for each chapter to distinguish presence from viewpoint.</p><div class="pov-heatmap"><table><thead><tr><th>Chapter / intended POV</th>'+povs.map(function(record){return'<th>'+DAL.escapeHtml(record.name)+'</th>';}).join('')+'</tr></thead><tbody>';
  report.rows.forEach(function(row){html+='<tr><th><button data-action="analytics-open-chapter" data-cid="'+row.chapter.id+'">'+DAL.escapeHtml(row.chapter.title)+'</button><select class="form-select" data-pov-chapter="'+row.chapter.id+'"><option value="">Not set'+(row.suggestion?' · suggested '+DAL.escapeHtml(row.suggestion.name):'')+'</option>'+povs.map(function(record){return'<option value="'+record.id+'"'+(row.chapter.povCharacterId===record.id?' selected':'')+'>'+DAL.escapeHtml(record.name)+'</option>';}).join('')+'<option value="first-person"'+(row.chapter.povCharacterId==='first-person'?' selected':'')+'>First-person narrator</option><option value="ensemble"'+(row.chapter.povCharacterId==='ensemble'?' selected':'')+'>Ensemble / omniscient</option></select></th>';var text=DAL.continuityText(row.chapter.contentHTML);povs.forEach(function(record){var count=DAL.povMentions(text,record),strength=count/maxMention;html+='<td><span class="pov-cell" style="--heat:'+strength.toFixed(2)+'" title="'+count+' mention'+(count===1?'':'s')+'">'+count+'</span></td>';});html+='</tr>';});
  html+='</tbody></table></div><h3>Chapter pacing</h3><div class="pacing-list">';
  report.rows.forEach(function(row){var pace=row.pacing,status=pace.score>report.target[1]?'faster than range':pace.score<report.target[0]?'slower than range':'within range';html+='<article class="pacing-row"><button data-action="analytics-open-chapter" data-cid="'+row.chapter.id+'"><strong>'+DAL.escapeHtml(row.chapter.title)+'</strong><span>'+pace.words+' words · '+pace.avgSentence+' words/sentence · '+Math.round(pace.dialogueRatio*100)+'% dialogue · '+pace.actionDensity+' action cues/100 words · '+pace.sceneBreaks+' scene breaks</span></button><div class="pace-meter"><span style="width:'+pace.score+'%"></span></div><b>'+pace.score+' <small>'+status+'</small></b></article>';});
  return html+'</div><div class="card analytics-guide"><strong>How the pace score works</strong><p>Shorter sentences and paragraphs, more dialogue, action verbs, and scene breaks raise it. Longer reflective passages lower it. A lower score is not a defect; use chapter-to-chapter changes to spot accidental lulls or rushed sections.</p></div></div>';
};

DAL._analyticsClickBase=DAL.handleStoryClick;
DAL.handleStoryClick=function(action,el,e){if(action==='analytics-open-chapter'){DAL.currentTool='manuscript';DAL.selectedChapterId=el.getAttribute('data-cid');DAL.render();return;}return DAL._analyticsClickBase(action,el,e);};
document.addEventListener('change',function(event){var el=event.target;if(!el.hasAttribute||!el.hasAttribute('data-pov-chapter'))return;var proj=DAL.state.projects[DAL.currentProjectId],chapter=(proj.chapters||[]).find(function(item){return item.id===el.getAttribute('data-pov-chapter');});if(chapter){chapter.povCharacterId=el.value;chapter.updatedAt=Date.now();DAL.saveState();}});
