/* Draft A Lore — book design, publication preview, EPUB, and print layout */
DAL = DAL || {};

DAL.BOOK_TRIMS={
  'paperback-6x9':{label:'Paperback 6 × 9 in',width:6,height:9,top:.65,right:.6,bottom:.7,left:.75,gutter:.15},
  'paperback-5x8':{label:'Paperback 5 × 8 in',width:5,height:8,top:.6,right:.5,bottom:.65,left:.65,gutter:.15},
  'a5':{label:'A5 paperback',width:5.83,height:8.27,top:.65,right:.55,bottom:.7,left:.7,gutter:.15},
  'hardcover-6x9':{label:'Hardcover 6 × 9 in',width:6,height:9,top:.75,right:.7,bottom:.8,left:.85,gutter:.2},
  'letter':{label:'US Letter manuscript',width:8.5,height:11,top:1,right:1,bottom:1,left:1,gutter:0}
};
DAL.BOOK_TYPE={classic:{label:'Classic serif',body:"Georgia, 'Times New Roman', serif",heading:"Georgia, 'Times New Roman', serif"},literary:{label:'Literary old style',body:"'Palatino Linotype', Palatino, Georgia, serif",heading:"'Palatino Linotype', Palatino, Georgia, serif"},modern:{label:'Modern sans',body:"Arial, Helvetica, sans-serif",heading:"Arial, Helvetica, sans-serif"},accessible:{label:'Accessible humanist',body:"'Trebuchet MS', Verdana, sans-serif",heading:"'Trebuchet MS', Verdana, sans-serif"},typewriter:{label:'Typewriter',body:"'Courier New', monospace",heading:"'Courier New', monospace"}};
DAL.ensureBookDesign=function(proj){
  var base=DAL.BOOK_TRIMS['paperback-6x9'],design=proj.bookDesign;if(!design||typeof design!=='object'||Array.isArray(design))design=proj.bookDesign={};
  if(!DAL.BOOK_TRIMS[design.trim])design.trim='paperback-6x9';if(!DAL.BOOK_TYPE[design.typography])design.typography='classic';
  ['width','height','top','right','bottom','left','gutter'].forEach(function(key){var fallback=DAL.BOOK_TRIMS[design.trim][key];design[key]=isFinite(Number(design[key]))?Math.max(0,Number(design[key])):fallback;});
  design.fontSize=Math.max(8,Math.min(24,Number(design.fontSize)||11));design.lineHeight=Math.max(1,Math.min(3,Number(design.lineHeight)||1.5));design.paragraphIndent=Math.max(0,Math.min(1,Number(design.paragraphIndent)||.25));design.dropCaps=design.dropCaps!==false;design.pageNumbers=design.pageNumbers!==false;design.chapterNewPage=design.chapterNewPage!==false;return design;
};
DAL.bookDesignVars=function(proj){var d=DAL.ensureBookDesign(proj),type=DAL.BOOK_TYPE[d.typography];return '--design-body:'+type.body+';--design-heading:'+type.heading+';--design-font-size:'+d.fontSize+'pt;--design-line-height:'+d.lineHeight+';--design-indent:'+d.paragraphIndent+'in;--design-pad-top:'+d.top+'in;--design-pad-right:'+d.right+'in;--design-pad-bottom:'+d.bottom+'in;--design-pad-left:'+d.left+'in';};
DAL.previewProfileControl=function(proj){var profiles=[['responsive','Responsive'],['phone','Android phone'],['tablet','Android tablet'],['kindle','Kindle'],['ipad','iPad'],['paperback','Paperback'],['hardcover','Hardcover']];return '<select class="form-select preview-profile" data-preview-profile title="Preview format" aria-label="Preview format">'+profiles.map(function(profile){return'<option value="'+profile[0]+'"'+(proj.previewProfile===profile[0]?' selected':'')+'>'+profile[1]+'</option>';}).join('')+'</select>';};

DAL.publicationCheck=function(proj){
  var d=DAL.ensureBookDesign(proj),checks=[],title=String((proj.cover&&proj.cover.title)||proj.name||'').trim(),author=String((proj.cover&&proj.cover.author)||(DAL.state.autoFillAuthor&&DAL.state.authorName)||'').trim(),chapters=proj.chapters||[],usableWidth=d.width-d.left-d.right-d.gutter,usableHeight=d.height-d.top-d.bottom;
  function add(level,label,detail){checks.push({level:level,label:label,detail:detail});}
  add(title?'ready':'error','Book title',title||'Add a title in Project Settings.');
  add(author?'ready':'warning','Author or pen name',author||'Add the public name you want printed in the book.');
  add(chapters.length?'ready':'error','Manuscript',chapters.length?chapters.length+' chapter'+(chapters.length===1?'':'s')+' included.':'Add at least one chapter before exporting.');
  var empty=chapters.filter(function(chapter){return !DAL.continuityText(chapter.contentHTML||'').trim();});
  if(empty.length)add('warning','Empty chapters',empty.map(function(chapter){return chapter.title;}).join(', '));
  var duplicate={};chapters.forEach(function(chapter){var key=String(chapter.title||'').trim().toLowerCase();if(key)duplicate[key]=(duplicate[key]||0)+1;});var duplicateTitles=Object.keys(duplicate).filter(function(key){return duplicate[key]>1;});
  if(duplicateTitles.length)add('warning','Repeated chapter titles',duplicateTitles.join(', '));
  add(usableWidth>=2.5&&usableHeight>=4?'ready':'error','Trim and margins',usableWidth.toFixed(2)+' × '+usableHeight.toFixed(2)+' in live text area.');
  var cover=DAL.bookPageImages(proj,1)[0];add(cover?'ready':'warning','Cover image',cover?'Assigned to page 1.':'Optional for draft exports; add one before a store-ready EPUB.');
  var counts={error:0,warning:0,ready:0};checks.forEach(function(check){counts[check.level]++;});return{checks:checks,counts:counts,ready:counts.error===0};
};

DAL.renderBookDesign=function(proj){var d=DAL.ensureBookDesign(proj),type=DAL.BOOK_TYPE[d.typography],preflight=DAL.publicationCheck(proj),html='<div class="book-design"><div class="section-header"><div><div class="section-title">Book Design</div><p class="writer-muted">Publication settings used by Book Preview, EPUB, and the print-ready PDF layout.</p></div><div class="writer-tool-actions"><button class="btn" data-action="ws-tool" data-tool="bookpreview">Preview</button><button class="btn" data-action="export-epub">Export EPUB</button><button class="btn primary" data-action="writer-print">Print-ready PDF</button></div></div>';
  html+='<div class="book-design-grid"><section class="card"><h3>Page</h3><div class="form-group"><label class="form-label">Trim preset</label><select class="form-select" data-book-design="trim">'+Object.keys(DAL.BOOK_TRIMS).map(function(key){return'<option value="'+key+'"'+(d.trim===key?' selected':'')+'>'+DAL.BOOK_TRIMS[key].label+'</option>';}).join('')+'</select></div><div class="writer-form-grid"><label class="form-group"><span class="form-label">Width (in)</span><input class="form-input" type="number" min="1" step=".01" data-book-design="width" value="'+d.width+'"></label><label class="form-group"><span class="form-label">Height (in)</span><input class="form-input" type="number" min="1" step=".01" data-book-design="height" value="'+d.height+'"></label></div></section>';
  html+='<section class="card"><h3>Margins</h3><div class="margin-grid">'+[['top','Top'],['right','Outside'],['bottom','Bottom'],['left','Inside'],['gutter','Gutter']].map(function(field){return'<label class="form-group"><span class="form-label">'+field[1]+' (in)</span><input class="form-input" type="number" min="0" step=".05" data-book-design="'+field[0]+'" value="'+d[field[0]]+'"></label>';}).join('')+'</div></section>';
  html+='<section class="card"><h3>Typography</h3><div class="form-group"><label class="form-label">Theme</label><select class="form-select" data-book-design="typography">'+Object.keys(DAL.BOOK_TYPE).map(function(key){return'<option value="'+key+'"'+(d.typography===key?' selected':'')+'>'+DAL.BOOK_TYPE[key].label+'</option>';}).join('')+'</select></div><div class="writer-form-grid"><label class="form-group"><span class="form-label">Body size (pt)</span><input class="form-input" type="number" min="8" max="24" step=".5" data-book-design="fontSize" value="'+d.fontSize+'"></label><label class="form-group"><span class="form-label">Line height</span><input class="form-input" type="number" min="1" max="3" step=".05" data-book-design="lineHeight" value="'+d.lineHeight+'"></label><label class="form-group"><span class="form-label">Paragraph indent (in)</span><input class="form-input" type="number" min="0" max="1" step=".05" data-book-design="paragraphIndent" value="'+d.paragraphIndent+'"></label></div><div class="book-type-sample" style="font-family:'+type.body+'"><strong style="font-family:'+type.heading+'">Chapter Heading</strong><p>The first line shows the selected body type, spacing, and paragraph rhythm.</p></div></section>';
  html+='<section class="card"><h3>Structure</h3><label class="check-row"><input type="checkbox" data-book-design="dropCaps"'+(d.dropCaps?' checked':'')+'> Drop capital on chapter openings</label><label class="check-row"><input type="checkbox" data-book-design="pageNumbers"'+(d.pageNumbers?' checked':'')+'> Page numbers</label><label class="check-row"><input type="checkbox" data-book-design="chapterNewPage"'+(d.chapterNewPage?' checked':'')+'> Start every chapter on a new page</label></section></div><section class="card publication-check"><div><h3>Publishing check</h3><p class="writer-muted">'+(preflight.ready?'No blocking export problems found.':'Fix the errors below before exporting.')+'</p></div><div class="publication-check-list">'+preflight.checks.map(function(check){return '<div class="publication-check-row '+check.level+'"><span class="publication-check-mark" aria-hidden="true">'+(check.level==='ready'?'✓':check.level==='error'?'!':'i')+'</span><div><strong>'+DAL.escapeHtml(check.label)+'</strong><p>'+DAL.escapeHtml(check.detail)+'</p></div></div>';}).join('')+'</div></section></div>';return html;
};

DAL.epubTextBytes=function(value){return new TextEncoder().encode(String(value));};
DAL.epubXml=function(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');};
DAL.epubXhtmlBody=function(html){var safe=DAL.sanitizeRichHTML(html||'');if(typeof XMLSerializer!=='undefined'&&document.createElement){var holder=document.createElement('div');holder.innerHTML=safe;var serializer=new XMLSerializer();return Array.from(holder.childNodes).map(function(node){return serializer.serializeToString(node);}).join('');}return safe.replace(/&nbsp;/gi,'&#160;').replace(/<(br|hr)(\s[^>]*)?>/gi,'<$1$2 />').replace(/<img([^>]*?)(?<!\/)\s*>/gi,'<img$1 />');};
DAL.epubImageCollector=function(){var files=[],manifest=[],counter=0,map={};return{replace:function(html,prefix){prefix=prefix===undefined?'../images/':prefix;return String(html||'').replace(/data:image\/(png|jpeg|jpg|webp|gif);base64,[A-Za-z0-9+/=\s]+/gi,function(uri,ext){var compact=uri.replace(/\s+/g,''),known=map[compact];if(known)return prefix+known;counter++;ext=ext.toLowerCase()==='jpg'?'jpeg':ext.toLowerCase();var filename='image-'+counter+'.'+(ext==='jpeg'?'jpg':ext),raw=atob(compact.slice(compact.indexOf(',')+1)),bytes=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);files.push({name:'EPUB/images/'+filename,data:bytes});manifest.push({id:'img'+counter,href:'images/'+filename,type:'image/'+ext});map[compact]=filename;return prefix+filename;});},files:files,manifest:manifest};};
DAL.epubFiles=function(proj){
  var d=DAL.ensureBookDesign(proj),type=DAL.BOOK_TYPE[d.typography],lang=proj.language||'en',title=(proj.cover&&proj.cover.title)||proj.name,author=(proj.cover&&proj.cover.author)||(DAL.state.autoFillAuthor?DAL.state.authorName:'')||'Unknown',collector=DAL.epubImageCollector(),chapters=[];
  var cover=DAL.bookPageImages(proj,1)[0],coverMarkup=cover?'<div class="cover"><img src="'+DAL.imageSrc(proj,cover)+'" alt="'+DAL.epubXml(cover.name||'Cover')+'" /></div>':'<div class="cover-title"><h1>'+DAL.epubXml(title)+'</h1><p>'+DAL.epubXml(author)+'</p></div>';coverMarkup=collector.replace(coverMarkup,'images/');
  (proj.chapters||[]).forEach(function(chapter,index){var body=DAL.writerPublishHTML?DAL.writerPublishHTML(proj,chapter):chapter.contentHTML;body=collector.replace(DAL.epubXhtmlBody(body));chapters.push({id:'chapter'+(index+1),href:'text/chapter-'+(index+1)+'.xhtml',title:chapter.title,body:body});});
  var css='body{font-family:'+type.body+';font-size:'+d.fontSize+'pt;line-height:'+d.lineHeight+';margin:5%;}h1,h2{font-family:'+type.heading+';page-break-after:avoid;}p{margin:0 0 .5em;text-indent:'+d.paragraphIndent+'in;}h1+p,h2+p{'+(d.dropCaps?'':'text-indent:0;')+'}.chapter>p:first-of-type::first-letter{'+(d.dropCaps?'float:left;font-size:3em;line-height:.85;margin-right:.08em;':'')+'}img{max-width:100%;height:auto}.cover{text-align:center}.cover img{max-height:95vh}.writer-page-break{page-break-after:always}';
  var nav='<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="'+DAL.epubXml(lang)+'"><head><title>Contents</title></head><body><nav epub:type="toc" id="toc"><h1>Contents</h1><ol><li><a href="cover.xhtml">Cover</a></li>'+chapters.map(function(chapter){return'<li><a href="'+chapter.href+'">'+DAL.epubXml(chapter.title)+'</a></li>';}).join('')+'</ol></nav></body></html>';
  var imageItems=collector.manifest.map(function(image,index){return'<item id="'+image.id+'" href="'+image.href+'" media-type="'+image.type+'"'+(cover&&index===0?' properties="cover-image"':'')+'/>';}).join('');
  var opf='<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id" xml:lang="'+DAL.epubXml(lang)+'"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="book-id">urn:draftalore:'+DAL.epubXml(proj.id)+'</dc:identifier><dc:title>'+DAL.epubXml(title)+'</dc:title><dc:creator>'+DAL.epubXml(author)+'</dc:creator><dc:language>'+DAL.epubXml(lang)+'</dc:language><meta property="dcterms:modified">'+new Date().toISOString().replace(/\.\d{3}Z$/,'Z')+'</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="css" href="style.css" media-type="text/css"/><item id="cover" href="cover.xhtml" media-type="application/xhtml+xml"/>'+chapters.map(function(chapter){return'<item id="'+chapter.id+'" href="'+chapter.href+'" media-type="application/xhtml+xml"/>';}).join('')+imageItems+'</manifest><spine><itemref idref="cover"/>'+chapters.map(function(chapter){return'<itemref idref="'+chapter.id+'"/>';}).join('')+'</spine></package>';
  var files=[{name:'mimetype',data:DAL.epubTextBytes('application/epub+zip')},{name:'META-INF/container.xml',data:DAL.epubTextBytes('<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="EPUB/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>')},{name:'EPUB/package.opf',data:DAL.epubTextBytes(opf)},{name:'EPUB/nav.xhtml',data:DAL.epubTextBytes(nav)},{name:'EPUB/style.css',data:DAL.epubTextBytes(css)},{name:'EPUB/cover.xhtml',data:DAL.epubTextBytes('<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" lang="'+DAL.epubXml(lang)+'"><head><title>Cover</title><link rel="stylesheet" href="style.css"/></head><body>'+coverMarkup+'</body></html>')}];
  chapters.forEach(function(chapter){files.push({name:'EPUB/'+chapter.href,data:DAL.epubTextBytes('<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" lang="'+DAL.epubXml(lang)+'"><head><title>'+DAL.epubXml(chapter.title)+'</title><link rel="stylesheet" href="../style.css"/></head><body><section class="chapter"><h1>'+DAL.epubXml(chapter.title)+'</h1>'+chapter.body+'</section></body></html>')});});return files.concat(collector.files);
};
DAL.downloadBytes=function(filename,bytes,mime){var blob=new Blob([bytes],{type:mime}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);};
DAL.exportEpub=function(proj){try{var files=DAL.epubFiles(proj),bytes=DAL.makeZip(files);DAL.downloadBytes(DAL.sanitizeFilename((proj.cover&&proj.cover.title)||proj.name)+'.epub',bytes,'application/epub+zip');DAL.toast('EPUB downloaded with '+(proj.chapters||[]).length+' chapters','success');}catch(error){DAL.toast('EPUB export failed: '+error.message,'error');}};
DAL.printBook=function(proj){
  var d=DAL.ensureBookDesign(proj),type=DAL.BOOK_TYPE[d.typography],title=(proj.cover&&proj.cover.title)||proj.name,author=(proj.cover&&proj.cover.author)||(DAL.state.autoFillAuthor?DAL.state.authorName:''),css='@page{size:'+d.width+'in '+d.height+'in;margin:'+d.top+'in '+d.right+'in '+d.bottom+'in '+(d.left+d.gutter)+'in}@page:left{margin-left:'+d.right+'in;margin-right:'+(d.left+d.gutter)+'in}@page:right{margin-left:'+(d.left+d.gutter)+'in;margin-right:'+d.right+'in}'+(d.pageNumbers?'@page{@bottom-center{content:counter(page);font:9pt '+type.body+'}}':'')+'body{font:'+d.fontSize+'pt/'+d.lineHeight+' '+type.body+';color:#000;background:#fff;margin:0}h1,h2{font-family:'+type.heading+';page-break-after:avoid}section.chapter{'+(d.chapterNewPage?'break-before:page;page-break-before:always;':'')+'}p{margin:0 0 .5em;text-indent:'+d.paragraphIndent+'in}section.chapter>p:first-of-type{text-indent:0}'+(d.dropCaps?'section.chapter>p:first-of-type::first-letter{float:left;font-size:3em;line-height:.85;margin-right:.08em}':'')+'img{max-width:100%;height:auto}.title-page{height:70vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;break-after:page}.writer-page-break{break-after:page}',body='<section class="title-page"><h1>'+DAL.escapeHtml(title)+'</h1>'+(author?'<p>'+DAL.escapeHtml(author)+'</p>':'')+'</section>'+(proj.chapters||[]).map(function(chapter){return'<section class="chapter"><h1>'+DAL.escapeHtml(chapter.title)+'</h1>'+(DAL.writerPublishHTML?DAL.writerPublishHTML(proj,chapter):chapter.contentHTML)+'</section>';}).join(''),win=window.open('','_blank');if(!win){DAL.toast('Allow the print window, then choose Save as PDF.','warning');return;}win.document.open();win.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+DAL.escapeHtml(title)+'</title><style>'+css+'</style></head><body>'+body+'</body></html>');win.document.close();win.focus();setTimeout(function(){win.print();},250);
};

DAL.registerActionHandler(function(action,el){var proj=DAL.state.projects[DAL.currentProjectId]||DAL.exportTarget&&DAL.exportTarget(el);if(action==='export-epub'){if(proj)DAL.exportEpub(proj);return true;}if(action==='writer-print'){if(proj)DAL.printBook(proj);return true;}return false;});
document.addEventListener('change',function(event){var el=event.target,proj=DAL.state.projects[DAL.currentProjectId];if(!proj)return;if(el.hasAttribute&&el.hasAttribute('data-preview-profile')){proj.previewProfile=el.value;DAL.saveState();DAL.render();return;}if(!el.hasAttribute||!el.hasAttribute('data-book-design'))return;var design=DAL.ensureBookDesign(proj),field=el.getAttribute('data-book-design');if(field==='trim'){design.trim=el.value;var preset=DAL.BOOK_TRIMS[el.value];['width','height','top','right','bottom','left','gutter'].forEach(function(key){design[key]=preset[key];});}else if(el.type==='checkbox')design[field]=el.checked;else if(['typography'].indexOf(field)>=0)design[field]=el.value;else design[field]=Number(el.value);proj.updatedAt=Date.now();DAL.saveState();DAL.render();});
