/* Manuscript review, reference and structured-writing tools. */
(function(){
  var COLORS = [['#fff59d','Yellow'],['#b9f6ca','Green'],['#b3e5fc','Blue'],['#f8bbd0','Pink'],['#d1c4e9','Purple'],['#ffcc80','Orange']];

  function project(){ return DAL.currentWriterProject && DAL.currentWriterProject(); }
  function data(proj){
    var d = DAL.writerProject(proj);
    ['highlights','bookmarks','footnotes','sources'].forEach(function(key){ if(!Array.isArray(d[key])) d[key]=[]; });
    if(!d.exportOptions) d.exportOptions={highlights:false,comments:false,footnotes:true,callouts:true};
    return d;
  }
  function editor(){ return document.getElementById('editorContent'); }
  function save(){ DAL.saveChapterContent(); DAL.captureWriterSelection(); }
  function restore(){ var sel=window.getSelection&&window.getSelection(); if(!sel||!DAL._writerRange)return false; try{sel.removeAllRanges();sel.addRange(DAL._writerRange);return true;}catch(e){return false;} }
  function unwrap(node){ var p=node.parentNode; if(!p)return; while(node.firstChild)p.insertBefore(node.firstChild,node);p.removeChild(node); }
  function insert(html){
    var ed=editor();if(!ed)return;ed.focus();restore();
    if(/^<(aside|table|blockquote|pre|ul|ol|hr|div)\b/i.test(html)&&DAL._writerRange){
      var range=DAL._writerRange.cloneRange(),top=range.commonAncestorContainer;if(top.nodeType===3)top=top.parentNode;
      while(top&&top.parentNode&&top.parentNode!==ed)top=top.parentNode;
      if(!range.collapsed)range.deleteContents();
      if(top&&top.parentNode===ed)range.setStartAfter(top);else{range.selectNodeContents(ed);range.collapse(false);}
      range.collapse(true);var fragment=range.createContextualFragment(html),last=fragment.lastChild;range.insertNode(fragment);
      if(last){range.setStartAfter(last);range.collapse(true);var sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);DAL._writerRange=range.cloneRange();}
    }else document.execCommand('insertHTML',false,html);
    save();
  }
  function selectedText(){ return DAL._writerRange ? String(DAL._writerRange) : ''; }

  DAL.captureWriterSelection=function(){
    var sel=window.getSelection&&window.getSelection(); if(!sel||!sel.rangeCount)return;
    var range=sel.getRangeAt(0), ed=editor();
    if(ed&&ed.contains(range.commonAncestorContainer)) DAL._writerRange=range.cloneRange();
  };

  DAL.renderAdvancedWriterToolbar=function(){
    var colors='<option value="">Highlight</option>'+COLORS.map(function(c){return '<option value="'+c[0]+'">'+c[1]+'</option>';}).join('')+'<option value="clear">Remove highlight</option>';
    return '<span class="tb-sep"></span><select class="writer-highlight-select" data-writer-control="highlight" aria-label="Highlight selected text">'+colors+'</select><input class="writer-highlight-custom" type="color" value="#fff59d" data-writer-control="highlight-custom" aria-label="Custom highlight color" title="Custom highlight color">'+
      '<button class="tb-btn" data-action="format-cmd" data-cmd="removeFormat" title="Clear formatting" aria-label="Clear formatting">Tx</button><button class="tb-btn" data-action="format-cmd" data-cmd="superscript" title="Superscript" aria-label="Superscript">x²</button><button class="tb-btn" data-action="format-cmd" data-cmd="subscript" title="Subscript" aria-label="Subscript">x₂</button><button class="tb-btn" data-action="format-cmd" data-cmd="outdent" title="Outdent" aria-label="Outdent">⇤</button><button class="tb-btn" data-action="format-cmd" data-cmd="indent" title="Indent" aria-label="Indent">⇥</button>'+
      '<button class="tb-btn" data-action="new-comment" title="Comment on selected text" aria-label="Add comment">💬</button><button class="tb-btn" data-action="world-lookup" title="Look up selected words in this world" aria-label="World lookup">🔍</button><button class="tb-btn" data-action="writer-link" title="Add external or internal link" aria-label="Add link">🔗</button><button class="tb-btn" data-action="format-cmd" data-cmd="unlink" title="Remove link" aria-label="Remove link">⛓</button>'+
      '<select class="writer-insert-select" data-writer-control="insert" aria-label="Insert structured content"><option value="">Insert…</option><option value="quote">Block quote</option><option value="note">Note callout</option><option value="important">Important callout</option><option value="warning">Warning callout</option><option value="rule">Rule / boxed text</option><option value="verse">Verse block</option><option value="number-lines">Number selected lines</option><option value="code">Code block</option><option value="checklist">Checklist</option><option value="table">Table…</option><option value="table-row-add">Table: add row</option><option value="table-row-remove">Table: remove row</option><option value="table-col-add">Table: add column</option><option value="table-col-remove">Table: remove column</option><option value="bookmark">Bookmark</option><option value="footnote">Footnote</option><option value="pagebreak">Page break</option></select>';
  };

  DAL.writerPublishHTML=function(proj,ch){var d=data(proj),opts=d.exportOptions,holder=document.createElement('div');holder.innerHTML=DAL.sanitizeRichHTML(ch.contentHTML||'');Array.from(holder.querySelectorAll('.writer-bookmark')).forEach(function(n){n.remove();});if(!opts.highlights)Array.from(holder.querySelectorAll('.writer-highlight')).forEach(unwrap);if(!opts.footnotes)Array.from(holder.querySelectorAll('.writer-footnote-ref')).forEach(function(n){n.remove();});if(!opts.callouts)Array.from(holder.querySelectorAll('.writer-callout')).forEach(unwrap);Array.from(holder.querySelectorAll('.writer-check')).forEach(function(n){n.removeAttribute('contenteditable');});if(opts.footnotes){var ids=Array.from(holder.querySelectorAll('[data-footnote-id]')).map(function(n){return n.getAttribute('data-footnote-id');}),notes=d.footnotes.filter(function(f){return ids.indexOf(f.id)>=0;});if(notes.length)holder.insertAdjacentHTML('beforeend','<hr><section class="writer-footnotes"><h3>Notes</h3><ol>'+notes.map(function(f){return '<li>'+DAL.escapeHtml(f.text)+'</li>';}).join('')+'</ol></section>');}if(opts.comments){var comments=d.comments.filter(function(c){return c.chapterId===ch.id;});if(comments.length)holder.insertAdjacentHTML('beforeend','<hr><section class="writer-comments"><h3>Annotations</h3><ol>'+comments.map(function(c){return '<li><strong>'+DAL.escapeHtml(c.label||'Note')+':</strong> '+DAL.escapeHtml(c.body||'')+(c.anchor?' <em>“'+DAL.escapeHtml(c.anchor)+'”</em>':'')+'</li>';}).join('')+'</ol></section>');}return holder.innerHTML;};
  DAL.writerExportControls=function(proj){var o=data(proj).exportOptions;return '<fieldset class="writer-export-options"><legend>Review marks in publishing exports</legend><label><input type="checkbox" data-writer-export="highlights"'+(o.highlights?' checked':'')+'> Include highlights</label><label><input type="checkbox" data-writer-export="comments"'+(o.comments?' checked':'')+'> Include comments</label><label><input type="checkbox" data-writer-export="footnotes"'+(o.footnotes?' checked':'')+'> Include footnotes</label><label><input type="checkbox" data-writer-export="callouts"'+(o.callouts?' checked':'')+'> Include callouts</label></fieldset>';};

  DAL.applyWriterHighlight=function(color){
    var ed=editor(); if(!ed||!restore()){DAL.toast('Select manuscript text first','info');return;}
    ed.focus(); document.execCommand('hiliteColor',false,color==='clear'?'transparent':color);
    var proj=project(), d=data(proj), live={};
    Array.from(ed.querySelectorAll('span[style],mark[style],.writer-highlight')).forEach(function(node){
      var bg=node.style.backgroundColor;
      if(!bg||bg==='transparent'||bg==='rgba(0, 0, 0, 0)'){ if(node.classList.contains('writer-highlight'))unwrap(node); return; }
      var id=node.getAttribute('data-highlight-id')||DAL.uid('highlight'); node.classList.add('writer-highlight');node.setAttribute('data-highlight-id',id);node.setAttribute('data-color',bg);live[id]=true;
      if(!d.highlights.some(function(h){return h.id===id;})) d.highlights.push({id:id,chapterId:DAL.selectedChapterId,color:bg,label:'',note:'',createdAt:Date.now()});
    });
    d.highlights=d.highlights.filter(function(h){return h.chapterId!==DAL.selectedChapterId||live[h.id];}); save(); DAL.toast(color==='clear'?'Highlight removed':'Text highlighted','success');
  };

  function editTable(kind){var range=DAL._writerRange,node=range&&range.commonAncestorContainer;if(node&&node.nodeType===3)node=node.parentElement;var cell=node&&node.closest&&node.closest('td,th');if(!cell){DAL.toast('Place the cursor inside a table first','info');return;}var row=cell.parentElement,table=row.closest('table'),index=Array.from(row.cells).indexOf(cell);if(kind==='table-row-add'){var added=table.insertRow(row.rowIndex+1);for(var i=0;i<row.cells.length;i++)added.insertCell().textContent='Cell';}else if(kind==='table-row-remove'){if(table.rows.length>1)row.remove();else DAL.toast('A table needs at least one row','info');}else if(kind==='table-col-add'){Array.from(table.rows).forEach(function(r){var n=r.insertCell(index+1);n.textContent=r.rowIndex===0?'Heading':'Cell';});}else if(kind==='table-col-remove'){if(row.cells.length>1)Array.from(table.rows).forEach(function(r){if(r.cells[index])r.deleteCell(index);});else DAL.toast('A table needs at least one column','info');}save();}

  function chapterMarkup(ch, fn){ var holder=document.createElement('div');holder.innerHTML=ch.contentHTML||'';fn(holder);ch.contentHTML=holder.innerHTML;ch.updatedAt=Date.now(); }
  function syncWriterRecords(proj,d){
    var liveHighlights={},liveBookmarks={},liveFootnotes={};
    (proj.chapters||[]).forEach(function(ch){var holder=document.createElement('div');holder.innerHTML=ch.contentHTML||'';
      Array.from(holder.querySelectorAll('[data-highlight-id]')).forEach(function(n){liveHighlights[n.getAttribute('data-highlight-id')]=ch.id;});
      Array.from(holder.querySelectorAll('[data-bookmark-id]')).forEach(function(n){liveBookmarks[n.getAttribute('data-bookmark-id')]=ch.id;});
      Array.from(holder.querySelectorAll('[data-footnote-id]')).forEach(function(n){liveFootnotes[n.getAttribute('data-footnote-id')]=ch.id;});
    });
    d.highlights=d.highlights.filter(function(x){return liveHighlights[x.id];});
    d.bookmarks=d.bookmarks.filter(function(x){return liveBookmarks[x.id];});
    d.footnotes=d.footnotes.filter(function(x){return liveFootnotes[x.id];});
    d.highlights.forEach(function(x){x.chapterId=liveHighlights[x.id];});
    d.bookmarks.forEach(function(x){x.chapterId=liveBookmarks[x.id];});
    d.footnotes.forEach(function(x){x.chapterId=liveFootnotes[x.id];});
    renumberFootnotes(proj,d);
  }
  function highlightRows(proj,d){
    return d.highlights.map(function(h){var ch=DAL.chapterById(proj,h.chapterId),excerpt='Detached highlight';if(ch)chapterMarkup({contentHTML:ch.contentHTML},function(holder){var n=holder.querySelector('[data-highlight-id="'+CSS.escape(h.id)+'"]');if(n)excerpt=(n.textContent||'').trim()||'Empty highlight';});return '<div class="writer-review-row"><button class="writer-review-jump" data-action="writer-highlight-jump" data-id="'+h.id+'"><span class="writer-swatch" style="background:'+DAL.escapeHtml(h.color||'#fff59d')+'"></span><strong>'+DAL.escapeHtml(excerpt.slice(0,100))+'</strong><small>'+DAL.escapeHtml((ch&&ch.title)||'Deleted chapter')+(h.label?' · '+DAL.escapeHtml(h.label):'')+'</small></button><button class="btn sm" data-action="writer-highlight-edit" data-id="'+h.id+'">Edit</button><button class="btn sm danger" data-action="writer-highlight-delete" data-id="'+h.id+'">×</button></div>';}).join('');
  }
  DAL.showWriterReview=function(){var proj=project(),d=data(proj);syncWriterRecords(proj,d);var h='<div class="writer-review-summary"><strong>'+d.highlights.length+'</strong> highlights <strong>'+d.comments.filter(function(c){return !c.resolved;}).length+'</strong> unresolved comments <strong>'+d.bookmarks.length+'</strong> bookmarks</div><h3>Highlights</h3><div class="writer-review-list">'+(highlightRows(proj,d)||'<p class="writer-muted">No highlights yet.</p>')+'</div><h3>Bookmarks</h3><div class="writer-review-list">'+(d.bookmarks.map(function(b){var ch=DAL.chapterById(proj,b.chapterId);return '<div class="writer-review-row"><button class="writer-review-jump" data-action="writer-bookmark-jump" data-id="'+b.id+'"><strong>'+DAL.escapeHtml(b.name||'Bookmark')+'</strong><small>'+DAL.escapeHtml((ch&&ch.title)||'Deleted chapter')+'</small></button><button class="btn sm danger" data-action="writer-bookmark-delete" data-id="'+b.id+'">×</button></div>';}).join('')||'<p class="writer-muted">No bookmarks yet.</p>')+'</div>';DAL.modal('Review & Annotations',h,{wide:true,footer:'<button class="btn" data-action="show-comments">Comments</button><button class="btn primary" data-action="close-modal">Done</button>'});};

  DAL.showWriterOutline=function(){var proj=project(),rows=[];(proj.chapters||[]).forEach(function(ch){rows.push('<button class="writer-outline-row chapter" data-action="writer-outline-jump" data-cid="'+ch.id+'"><strong>'+DAL.escapeHtml(ch.title)+'</strong></button>');var holder=document.createElement('div');holder.innerHTML=ch.contentHTML||'';Array.from(holder.querySelectorAll('h1,h2,h3,h4')).forEach(function(n,i){rows.push('<button class="writer-outline-row '+n.tagName.toLowerCase()+'" data-action="writer-outline-jump" data-cid="'+ch.id+'" data-heading="'+i+'">'+DAL.escapeHtml(n.textContent||'Untitled heading')+'</button>');});});DAL.modal('Document Outline',rows.join('')||'<p class="writer-muted">Add chapters or headings to build an outline.</p>',{wide:true,footer:'<button class="btn primary" data-action="close-modal">Done</button>'});};

  DAL.showWriterLink=function(){var proj=project(),targets=[];(proj.chapters||[]).forEach(function(x){targets.push(['chapter',x.id,'Chapter: '+x.title]);});(proj.characters||[]).forEach(function(x){targets.push(['character',x.id,'Character: '+x.name]);});((proj.lore||{}).entries||[]).forEach(function(x){targets.push(['lore',x.id,'Lore: '+x.title]);});(proj.plots||[]).forEach(function(x){targets.push(['plot',x.id,'Plot: '+x.title]);});((proj.adventure||{}).nodes||[]).forEach(function(x){targets.push(['scene',x.id,'Scene: '+x.title]);});var opts=targets.map(function(x){return '<option value="'+x[0]+':'+x[1]+'">'+DAL.escapeHtml(x[2])+'</option>';}).join('');DAL.modal('Add Link','<div class="form-group"><label class="form-label">Web or email address</label><input class="form-input" id="writerLinkUrl" placeholder="https://example.com"></div><div class="writer-or">or</div><div class="form-group"><label class="form-label">Draft A Lore record</label><select class="form-select" id="writerInternalLink"><option value="">Choose a project record…</option>'+opts+'</select></div>',{footer:'<button class="btn" data-action="close-modal">Cancel</button><button class="btn primary" data-action="writer-link-save">Add link</button>'});};

  function renumberFootnotes(proj,d){d.footnotes.forEach(function(f,i){f.number=i+1;});(proj.chapters||[]).forEach(function(ch){var holder=document.createElement('div'),before=ch.contentHTML||'';holder.innerHTML=before;Array.from(holder.querySelectorAll('[data-footnote-id]')).forEach(function(n){var f=d.footnotes.find(function(x){return x.id===n.getAttribute('data-footnote-id');});if(f)n.textContent='['+f.number+']';});if(holder.innerHTML!==before){ch.contentHTML=holder.innerHTML;ch.updatedAt=Date.now();}});}
  DAL.showWriterReferences=function(){var proj=project(),d=data(proj);syncWriterRecords(proj,d);var foot=d.footnotes.map(function(f){return '<div class="writer-reference-row"><strong>['+f.number+']</strong><span>'+DAL.escapeHtml(f.text)+'</span><button class="btn sm" data-action="writer-footnote-edit" data-id="'+f.id+'">Edit</button><button class="btn sm danger" data-action="writer-footnote-delete" data-id="'+f.id+'">×</button></div>';}).join(''),src=d.sources.map(function(s){return '<div class="writer-reference-row"><div><strong>'+DAL.escapeHtml(s.title||'Untitled source')+'</strong><small>'+DAL.escapeHtml([s.author,s.reference,s.url].filter(Boolean).join(' · '))+'</small><p>'+DAL.escapeHtml(s.note||'')+'</p></div><button class="btn sm" data-action="writer-source-edit" data-id="'+s.id+'">Edit</button><button class="btn sm danger" data-action="writer-source-delete" data-id="'+s.id+'">×</button></div>';}).join('');DAL.modal('References','<div class="writer-toolbar"><button class="btn primary" data-action="writer-source-add">Add source</button></div><h3>Footnotes</h3>'+(foot||'<p class="writer-muted">No footnotes yet.</p>')+'<h3>Sources</h3>'+(src||'<p class="writer-muted">No source notes yet.</p>'),{wide:true,footer:'<button class="btn primary" data-action="close-modal">Done</button>'});};
  DAL.writerFootnoteEditor=function(note){note=note||{};DAL._writerFootnoteId=note.id||null;DAL.modal(note.id?'Edit Footnote':'Add Footnote','<label class="form-label">Footnote text</label><textarea class="form-textarea" id="writerFootnoteText">'+DAL.escapeHtml(note.text||'')+'</textarea>',{footer:'<button class="btn" data-action="writer-references">Cancel</button><button class="btn primary" data-action="writer-footnote-save">'+(note.id?'Save footnote':'Add footnote')+'</button>'});};
  DAL.writerSourceEditor=function(source){source=source||{};DAL._writerSourceId=source.id||null;DAL.modal(source.id?'Edit Source':'Add Source','<div class="form-group"><label class="form-label">Title</label><input class="form-input" id="sourceTitle" value="'+DAL.escapeHtml(source.title||'')+'"></div><div class="form-group"><label class="form-label">Author / creator</label><input class="form-input" id="sourceAuthor" value="'+DAL.escapeHtml(source.author||'')+'"></div><div class="writer-form-grid"><div class="form-group"><label class="form-label">Edition / publication</label><input class="form-input" id="sourceEdition" value="'+DAL.escapeHtml(source.edition||'')+'"></div><div class="form-group"><label class="form-label">Date</label><input class="form-input" id="sourceDate" value="'+DAL.escapeHtml(source.date||'')+'"></div></div><div class="form-group"><label class="form-label">Page, verse, or reference</label><input class="form-input" id="sourceReference" value="'+DAL.escapeHtml(source.reference||'')+'"></div><div class="form-group"><label class="form-label">URL</label><input class="form-input" id="sourceUrl" value="'+DAL.escapeHtml(source.url||'')+'"></div><div class="form-group"><label class="form-label">Research note</label><textarea class="form-textarea" id="sourceNote">'+DAL.escapeHtml(source.note||'')+'</textarea></div>',{footer:'<button class="btn" data-action="writer-references">Cancel</button><button class="btn primary" data-action="writer-source-save">Save source</button>'});};

  DAL.registerActionHandler(function(action,el){var proj=project(),d=proj&&data(proj),id;
    if(action==='writer-review'){DAL.showWriterReview();return true;} if(action==='writer-outline'){DAL.showWriterOutline();return true;} if(action==='writer-references'){DAL.showWriterReferences();return true;}
    if(action==='writer-highlight'){if(el.value)DAL.applyWriterHighlight(el.value);el.value='';return true;} if(action==='writer-highlight-custom'){DAL.applyWriterHighlight(el.value);return true;}
    if(action==='writer-link'){DAL.showWriterLink();return true;} if(action==='writer-link-save'){var url=(document.getElementById('writerLinkUrl')||{}).value||'',internal=(document.getElementById('writerInternalLink')||{}).value||'',href=url.trim();if(internal)href='#dal:'+internal;if(!/^(https?:\/\/|mailto:|#dal:)/i.test(href)){DAL.toast('Enter a complete https://, mailto:, or internal link','warning');return true;}DAL.closeModal();restore();var label=selectedText()||href;document.execCommand('insertHTML',false,'<a href="'+DAL.escapeHtml(href)+'">'+DAL.escapeHtml(label)+'</a>');save();return true;}
    if(action==='writer-insert'){var kind=el.value;el.value='';if(!kind)return true;if(kind.indexOf('table-')===0){editTable(kind);return true;}if(kind==='table'){DAL.modal('Insert Table','<div class="writer-form-grid"><label>Rows<input class="form-input" id="writerTableRows" type="number" min="1" max="20" value="3"></label><label>Columns<input class="form-input" id="writerTableCols" type="number" min="1" max="10" value="3"></label></div>',{footer:'<button class="btn" data-action="close-modal">Cancel</button><button class="btn primary" data-action="writer-table-save">Insert table</button>'});return true;}if(kind==='bookmark'){DAL.modal('Add Bookmark','<label class="form-label">Bookmark name</label><input class="form-input" id="writerBookmarkName" value="'+DAL.escapeHtml(selectedText().slice(0,80))+'">',{footer:'<button class="btn" data-action="close-modal">Cancel</button><button class="btn primary" data-action="writer-bookmark-save">Add bookmark</button>'});return true;}if(kind==='footnote'){DAL.writerFootnoteEditor();return true;}if(kind==='number-lines'){var lines=selectedText().split(/\r?\n/).filter(function(line){return line.trim();});if(!lines.length)lines=['First line','Second line'];insert('<div class="writer-numbered-lines">'+lines.map(function(line,i){return '<div><span contenteditable="false">'+(i+1)+'</span>'+DAL.escapeHtml(line)+'</div>';}).join('')+'</div><p><br></p>');return true;}var blocks={quote:'<blockquote>Quote…</blockquote>',note:'<aside class="writer-callout writer-note"><strong>Note</strong><p>Write your note…</p></aside>',important:'<aside class="writer-callout writer-important"><strong>Important</strong><p>Write here…</p></aside>',warning:'<aside class="writer-callout writer-warning"><strong>Warning</strong><p>Write here…</p></aside>',rule:'<aside class="writer-callout writer-rule"><strong>Rule / Boxed Text</strong><p>Write here…</p></aside>',verse:'<blockquote class="writer-verse">1. First line<br>2. Second line</blockquote>',code:'<pre><code>Code or monospaced text</code></pre>',checklist:'<ul class="writer-checklist"><li><span class="writer-check" data-checked="false" contenteditable="false">☐</span> Task</li></ul>',pagebreak:'<hr class="writer-page-break">'};insert(blocks[kind]||'');return true;}
    if(action==='writer-table-save'){var rows=Math.max(1,Math.min(20,parseInt((document.getElementById('writerTableRows')||{}).value)||3)),cols=Math.max(1,Math.min(10,parseInt((document.getElementById('writerTableCols')||{}).value)||3)),html='<table class="writer-table"><tbody>';for(var r=0;r<rows;r++){html+='<tr>';for(var c=0;c<cols;c++)html+=(r===0?'<th>Heading</th>':'<td>Cell</td>');html+='</tr>';}DAL.closeModal();insert(html+'</tbody></table><p><br></p>');return true;}
    if(action==='writer-bookmark-save'){id=DAL.uid('bookmark');var name=(document.getElementById('writerBookmarkName')||{}).value||'Bookmark';d.bookmarks.push({id:id,chapterId:DAL.selectedChapterId,name:name,createdAt:Date.now()});DAL.closeModal();insert('<span class="writer-bookmark" id="dal-bookmark-'+id+'" data-bookmark-id="'+id+'" contenteditable="false" title="'+DAL.escapeHtml(name)+'">🔖</span>');return true;}
    if(action==='writer-footnote-save'){var text=(document.getElementById('writerFootnoteText')||{}).value||'';if(!text.trim()){DAL.toast('Enter footnote text','warning');return true;}id=DAL._writerFootnoteId;var note=id&&d.footnotes.find(function(x){return x.id===id;});if(note){note.text=text.trim();DAL._writerFootnoteId=null;DAL.saveState();DAL.showWriterReferences();return true;}id=DAL.uid('footnote');d.footnotes.push({id:id,chapterId:DAL.selectedChapterId,text:text.trim(),number:d.footnotes.length+1,createdAt:Date.now()});DAL._writerFootnoteId=null;DAL.closeModal();insert('<sup class="writer-footnote-ref" data-footnote-id="'+id+'" contenteditable="false">['+d.footnotes.length+']</sup>');return true;}
    if(action==='writer-highlight-jump'||action==='writer-bookmark-jump'){id=el.getAttribute('data-id');var rec=(action==='writer-highlight-jump'?d.highlights:d.bookmarks).find(function(x){return x.id===id;});if(rec){DAL.selectedChapterId=rec.chapterId;DAL.currentTool='manuscript';DAL.closeModal();DAL.render();setTimeout(function(){var target=document.querySelector(action==='writer-highlight-jump'?'[data-highlight-id="'+CSS.escape(id)+'"]':'[data-bookmark-id="'+CSS.escape(id)+'"]');if(target){target.scrollIntoView({block:'center'});target.classList.add('writer-flash');setTimeout(function(){target.classList.remove('writer-flash');},1200);}},80);}return true;}
    if(action==='writer-outline-jump'){var cid=el.getAttribute('data-cid'),heading=parseInt(el.getAttribute('data-heading'));DAL.selectedChapterId=cid;DAL.closeModal();DAL.render();if(!isNaN(heading))setTimeout(function(){var heads=editor().querySelectorAll('h1,h2,h3,h4');if(heads[heading])heads[heading].scrollIntoView({block:'center'});},80);return true;}
    if(action==='comment-jump'){id=el.getAttribute('data-comment-id');var comment=d.comments.find(function(x){return x.id===id;});if(comment&&comment.anchor){var commentChapter=DAL.chapterById(proj,comment.chapterId),plain=commentChapter&&DAL.plainChapter(commentChapter)||'',at=plain.indexOf(comment.anchor);if(at>=0)DAL.openFindMatch({cid:comment.chapterId,text:plain,index:at,length:comment.anchor.length});else DAL.toast('The original text was changed or removed; the annotation is still saved.','info');}return true;}
    if(action==='writer-highlight-edit'){id=el.getAttribute('data-id');var h=d.highlights.find(function(x){return x.id===id;});if(h){DAL._writerHighlightId=id;DAL.modal('Edit Highlight','<label class="form-label">Color</label><input type="color" class="form-input" id="highlightEditColor" value="'+DAL.escapeHtml(h.color||'#fff59d')+'"><label class="form-label">Label</label><input class="form-input" id="highlightEditLabel" value="'+DAL.escapeHtml(h.label||'')+'" placeholder="To revise, research, important…"><label class="form-label">Note</label><textarea class="form-textarea" id="highlightEditNote">'+DAL.escapeHtml(h.note||'')+'</textarea>',{footer:'<button class="btn" data-action="writer-review">Cancel</button><button class="btn primary" data-action="writer-highlight-save">Save</button>'});}return true;}
    if(action==='writer-highlight-save'){id=DAL._writerHighlightId;var hh=d.highlights.find(function(x){return x.id===id;});if(hh){hh.color=document.getElementById('highlightEditColor').value;hh.label=document.getElementById('highlightEditLabel').value;hh.note=document.getElementById('highlightEditNote').value;var ch=DAL.chapterById(proj,hh.chapterId);if(ch)chapterMarkup(ch,function(holder){var n=holder.querySelector('[data-highlight-id="'+CSS.escape(id)+'"]');if(n){n.style.backgroundColor=hh.color;n.setAttribute('data-color',hh.color);}});DAL.saveState();DAL.showWriterReview();}return true;}
    if(action==='writer-highlight-delete'){id=el.getAttribute('data-id');var gone=d.highlights.find(function(x){return x.id===id;});if(gone){var ch=DAL.chapterById(proj,gone.chapterId);if(ch)chapterMarkup(ch,function(holder){var n=holder.querySelector('[data-highlight-id="'+CSS.escape(id)+'"]');if(n)unwrap(n);});d.highlights=d.highlights.filter(function(x){return x.id!==id;});DAL.saveState();DAL.showWriterReview();}return true;}
    if(action==='writer-bookmark-delete'){id=el.getAttribute('data-id');var b=d.bookmarks.find(function(x){return x.id===id;});if(b){var bch=DAL.chapterById(proj,b.chapterId);if(bch)chapterMarkup(bch,function(holder){var n=holder.querySelector('[data-bookmark-id="'+CSS.escape(id)+'"]');if(n)n.remove();});d.bookmarks=d.bookmarks.filter(function(x){return x.id!==id;});DAL.saveState();DAL.showWriterReview();}return true;}
    if(action==='writer-footnote-delete'){id=el.getAttribute('data-id');(proj.chapters||[]).forEach(function(ch){chapterMarkup(ch,function(holder){Array.from(holder.querySelectorAll('[data-footnote-id="'+CSS.escape(id)+'"]')).forEach(function(n){n.remove();});});});d.footnotes=d.footnotes.filter(function(x){return x.id!==id;});renumberFootnotes(proj,d);DAL.saveState();DAL.showWriterReferences();return true;}
    if(action==='writer-footnote-edit'){id=el.getAttribute('data-id');DAL.writerFootnoteEditor(d.footnotes.find(function(x){return x.id===id;}));return true;}
    if(action==='writer-source-add'){DAL.writerSourceEditor();return true;} if(action==='writer-source-edit'){id=el.getAttribute('data-id');DAL.writerSourceEditor(d.sources.find(function(x){return x.id===id;}));return true;}
    if(action==='writer-source-save'){id=DAL._writerSourceId;var src=id&&d.sources.find(function(x){return x.id===id;});if(!src){src={id:DAL.uid('source'),createdAt:Date.now()};d.sources.push(src);}src.title=document.getElementById('sourceTitle').value;src.author=document.getElementById('sourceAuthor').value;src.edition=document.getElementById('sourceEdition').value;src.date=document.getElementById('sourceDate').value;src.reference=document.getElementById('sourceReference').value;src.url=document.getElementById('sourceUrl').value;src.note=document.getElementById('sourceNote').value;DAL.saveState();DAL.showWriterReferences();return true;}
    if(action==='writer-source-delete'){id=el.getAttribute('data-id');d.sources=d.sources.filter(function(x){return x.id!==id;});DAL.saveState();DAL.showWriterReferences();return true;}
    if(action==='writer-print'){var printable='<!doctype html><html><head><title>'+DAL.escapeHtml(proj.name)+'</title><style>body{max-width:760px;margin:40px auto;font:12pt/1.6 Georgia,serif}h1,h2{page-break-after:avoid}.writer-callout{border:1px solid #777;padding:12px;margin:12px 0}.writer-table{border-collapse:collapse;width:100%}.writer-table th,.writer-table td{border:1px solid #777;padding:6px}.writer-page-break{page-break-after:always;border:0}.writer-highlight{color:#111}@media print{button{display:none}}</style></head><body><h1>'+DAL.escapeHtml((proj.cover&&proj.cover.title)||proj.name)+'</h1>'+(proj.chapters||[]).map(function(ch){return '<h2>'+DAL.escapeHtml(ch.title)+'</h2>'+DAL.writerPublishHTML(proj,ch);}).join('')+'</body></html>',win=window.open('','_blank');if(!win){DAL.toast('Allow pop-ups to open the print copy.','warning');return true;}win.document.write(printable);win.document.close();win.focus();win.print();return true;}
    return false;
  });

  document.addEventListener('selectionchange',function(){DAL.captureWriterSelection();var sel=window.getSelection&&window.getSelection(),out=document.getElementById('selectionStats');if(out){var text=sel&&editor()&&editor().contains(sel.anchorNode)?String(sel).trim():'';out.textContent=text?(text.split(/\s+/).length+' selected words · '+text.length+' characters'):'';}});
  document.addEventListener('change',function(e){var control=e.target.getAttribute&&e.target.getAttribute('data-writer-control');if(control==='highlight'){if(e.target.value)DAL.applyWriterHighlight(e.target.value);e.target.value='';}else if(control==='highlight-custom')DAL.applyWriterHighlight(e.target.value);else if(control==='insert')DAL.runAction('writer-insert',e.target,e);});
  document.addEventListener('change',function(e){var key=e.target.getAttribute&&e.target.getAttribute('data-writer-export'),proj=project();if(key&&proj){data(proj).exportOptions[key]=e.target.checked;DAL.saveState(true);}});
  document.addEventListener('click',function(e){var box=e.target.closest&&e.target.closest('.writer-check');if(!box)return;box.setAttribute('data-checked',box.getAttribute('data-checked')==='true'?'false':'true');box.textContent=box.getAttribute('data-checked')==='true'?'☑':'☐';save();});
  document.addEventListener('click',function(e){var link=e.target.closest&&e.target.closest('#editorContent a[href]');if(!link||!(e.ctrlKey||e.metaKey))return;var href=link.getAttribute('href')||'';e.preventDefault();if(href.indexOf('#dal:')!==0){if(/^https?:\/\//i.test(href))window.open(href,'_blank','noopener');else if(/^mailto:/i.test(href))window.location.href=href;return;}var parts=href.slice(5).split(':'),kind=parts.shift(),id=parts.join(':'),proj=project();if(kind==='chapter'){DAL.selectedChapterId=id;DAL.currentTool='manuscript';}else if(kind==='character'){DAL.selectedCharId=id;DAL.currentTool='characters';}else if(kind==='lore'){DAL.selectedLoreEntry=id;DAL.currentTool='lore';}else if(kind==='plot'){DAL.selectedPlotId=id;DAL.currentTool='plots';}else if(kind==='scene'){DAL.selectedNodeId=id;DAL.currentTool='storygraph';}if(proj)DAL.render();});
})();
