const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

function api(){const document={addEventListener(){},createElement(){return{};}};const sandbox={DAL:{},document,window:{},navigator:{},localStorage:{},indexedDB:{},console,Date,Blob,Promise,setTimeout,clearTimeout,TextEncoder,TextDecoder,Uint8Array,atob,URL};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','src','core.js'),'utf8'),sandbox);const DAL=sandbox.DAL;DAL.state=DAL.defaultState();DAL.registerActionHandler=function(){};DAL.handleStoryClick=function(){};DAL.bookPageImages=function(){return[];};DAL.imageSrc=function(){return'';};DAL.sanitizeRichHTML=value=>String(value||'');DAL.writerPublishHTML=(project,chapter)=>chapter.contentHTML;vm.runInContext(fs.readFileSync(path.join(__dirname,'..','src','publishing-tools.js'),'utf8'),sandbox);return DAL;}

test('book design presets create complete printable measurements',()=>{const DAL=api(),project=DAL.defaultProject('Book','novel'),design=DAL.ensureBookDesign(project);assert.equal(design.trim,'paperback-6x9');assert.equal(design.width,6);assert.equal(design.height,9);assert.ok(design.left>design.right);assert.equal(design.dropCaps,true);});

test('EPUB export contains the required EPUB 3 structure and ordered chapters',()=>{const DAL=api(),project=DAL.defaultProject('Book','novel');project.language='en';project.cover={title:'A & B',author:'Author'};project.chapters=[{id:'one',title:'First',contentHTML:'<p>Hello &amp; welcome.</p>'},{id:'two',title:'Second',contentHTML:'<p>Goodbye.</p>'}];const files=DAL.epubFiles(project),names=Array.from(files,file=>file.name),decode=value=>new TextDecoder().decode(value);assert.equal(names[0],'mimetype');assert.equal(decode(files[0].data),'application/epub+zip');assert.ok(names.includes('META-INF/container.xml'));assert.ok(names.includes('EPUB/package.opf'));assert.ok(names.includes('EPUB/nav.xhtml'));assert.ok(names.includes('EPUB/text/chapter-1.xhtml'));assert.ok(names.includes('EPUB/text/chapter-2.xhtml'));const packageFile=files.find(file=>file.name==='EPUB/package.opf');assert.match(decode(packageFile.data),/<dc:title>A &amp; B<\/dc:title>/);assert.match(decode(packageFile.data),/version="3.0"/);});

test('publication preview profiles are stored independently from manuscript data',()=>{const DAL=api(),project=DAL.defaultProject('Book','novel');project.previewProfile='kindle';const control=DAL.previewProfileControl(project);assert.match(control,/value="kindle" selected/);assert.equal(project.chapters.length,0);});

test('publishing preflight blocks missing manuscripts and clears after real content is added',()=>{const DAL=api(),project=DAL.defaultProject('Book','novel');DAL.continuityText=value=>String(value||'').replace(/<[^>]+>/g,' ').trim();DAL.bookPageImages=()=>[];let report=DAL.publicationCheck(project);assert.equal(report.ready,false);assert.ok(report.counts.error>0);project.cover.author='Writer';project.chapters=[{id:'one',title:'One',contentHTML:'<p>A real chapter.</p>'}];report=DAL.publicationCheck(project);assert.equal(report.ready,true);assert.equal(report.counts.error,0);});
